# Generated by Django 4.0.4 on 2022-05-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_uk_pif'),
    ]

    operations = [
        migrations.AddField(
            model_name='uk',
            name='uk_lastaccess',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
