# Generated by Django 4.0.4 on 2022-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_uk_uk_lastaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uk',
            name='uk_ogrn',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
