# Generated by Django 4.0.4 on 2022-05-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_uk_uk_ogrn'),
    ]

    operations = [
        migrations.CreateModel(
            name='formsmon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('selector', models.CharField(max_length=200)),
                ('regexp', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='pifmon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('extractor', models.CharField(max_length=200)),
                ('selector', models.CharField(max_length=200)),
                ('regexp', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='pif',
            name='pif_lasfupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='uk',
            name='uk_lastupdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
