# Generated by Django 4.0.4 on 2022-05-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_formsmon_pifmon_pif_pif_lasfupdate_uk_uk_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pifmon',
            name='sites',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
