# Generated by Django 4.0.4 on 2022-05-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alter_pifmon_extractor_alter_pifmon_regexp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('extractor', models.CharField(blank=True, max_length=200)),
                ('selector', models.CharField(blank=True, max_length=200)),
                ('regexp', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.rtype')),
            ],
        ),
        migrations.DeleteModel(
            name='formsmon',
        ),
        migrations.DeleteModel(
            name='pifmon',
        ),
        migrations.AddField(
            model_name='pif',
            name='pif_checkpage',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='uk',
            name='uk_checkpage',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='rule',
            name='uk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.uk'),
        ),
        migrations.AddField(
            model_name='checklog',
            name='pif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.pif'),
        ),
        migrations.AddField(
            model_name='checklog',
            name='uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.uk'),
        ),
    ]
