# Generated by Django 4.0.4 on 2022-06-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_monitoringlog_uk_uk_site_error_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uk',
            name='uk_site_unavailable_code',
            field=models.IntegerField(blank=True),
        ),
    ]
