# Generated by Django 4.0.4 on 2022-06-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_alter_uk_uk_site_unavailable_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringlog',
            name='errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitoringlog',
            name='unavailable',
            field=models.IntegerField(default=0),
        ),
    ]
