# Generated by Django 4.0.4 on 2022-07-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_alter_monitoringlog_errors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PUCB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pucb_npp', models.IntegerField()),
                ('pucb_name', models.CharField(max_length=150)),
                ('pucb_inn', models.CharField(max_length=12)),
                ('pucb_sitetype', models.CharField(max_length=5)),
                ('pucb_site', models.CharField(max_length=500)),
            ],
        ),
    ]
