# Generated by Django 4.0.4 on 2022-07-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_pucb'),
    ]

    operations = [
        migrations.AddField(
            model_name='pucb',
            name='pucb_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
