# Generated by Django 4.0.4 on 2022-07-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_pucb_pucb_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='pucb',
            name='pucb_lastupdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
