# Generated by Django 4.0.4 on 2022-07-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_pucb_pucb_lastupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pucb',
            old_name='pucb_lastupdate',
            new_name='pucb_lastaccess',
        ),
    ]
