# Generated by Django 4.0.4 on 2022-10-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_rename_pucb_lastupdate_pucb_pucb_lastaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pif',
            name='pif_npdu',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pif',
            name='pif_prefnames',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pif',
            name='pif_prefpdu',
            field=models.TextField(blank=True),
        ),
    ]
