# Generated by Django 4.0.4 on 2022-10-24 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_alter_pif_pif_npdu_alter_pif_pif_prefnames_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uk',
            old_name='uk_checkpage',
            new_name='uk_extractor',
        ),
    ]
