# Generated by Django 4.0.4 on 2022-10-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_rename_uk_checkpage_uk_uk_extractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklog',
            name='doc_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklog',
            name='doc_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklog',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
