# Generated by Django 4.0.4 on 2022-10-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_checklog_doc_date_checklog_doc_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklog',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
