# Generated by Django 4.0.4 on 2022-10-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_checklog_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklog',
            old_name='date',
            new_name='date_log',
        ),
    ]
