# Generated by Django 4.0.4 on 2022-10-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_rename_date_checklog_date_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklog',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
