# Generated by Django 4.0.4 on 2022-10-31 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_checklog_acknowledged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklog',
            name='pif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.pif'),
        ),
        migrations.AlterField(
            model_name='checklog',
            name='uk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.uk'),
        ),
    ]
