# Generated by Django 4.0.4 on 2022-11-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0023_alter_checklog_pif_alter_checklog_uk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pif',
            name='pif_status',
            field=models.CharField(max_length=23),
        ),
    ]
